# Generated by Django 3.0.3 on 2020-03-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='City',
        ),
    ]
